# Generated by Django 5.0.2 on 2024-03-17 17:48

import petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='pet_photos/', validators=[petstagram.photos.validators.MaxFileSizeValidator(limit_value=5242880)]),
        ),
    ]
